### ISSUE TITLE
How do you find the address of camera control ?

### ISSUE THREAD

**Issue by shinshiner** [Spl3en/NierAutomataFreeCamera#1]
Hello, thanks for your great script, I'm trying some game hacking recently and I'm very curious about the way to get such address namely `0x141415B90` in your code. Different from some numerical attributes, which can be scanned in Cheat Engine by changing the corresponding values, such functional address might not be found by this way. Would you mind specify the process or tools ?

**Comment by Spl3en** [comment]
You need to learn reverse engineering with a static analysis approach (with tools such as IDA Pro or Ghidra). Dynamic analysis tools (debuggers or cheat engine) aren't good enough for finding such values. You need a very good understanding in x86, C, and C++, including their internals (memory layouts, RTTI, compilation optimizations, etc)

I haven't found this particular value (credits go to [@Wunkolo](https://twitter.com/Wunkolo/status/843387447656435712)) and I never tried reversing N:A binary, so I can't tell you the exact process for this one.

If I had to find it, I would try to modify the camera angle in game, find some instructions in cheatengine that writes to these values, then open un the binary in IDA Pro and start reversing from these instructions. Eventually I would end up in the Camera engine, which probably contains a method that enables a "freeCamera" mode thanks to the global variable that is statically found at 0x141415B90 in the current N:A binary. 
I suspect this value to be used for other purposes too, as `0x80000000` sounds like a flag value, so depending of the values of the bits of that variable, the camera behavior may change to other modes.

**Comment by shinshiner** [comment]
Thanks a lot, that does help to me, and I guess this flag value may be relevant to the flags in debug build. I have modified the value of `0x80000000` but seems no other effects. I will try some other addresses and values according to the debug menu.
